### ISSUE TITLE
Is there a problem with the firmware of OpenMV3?

### ISSUE THREAD

**Issue by zz2633105** [openmv/openmv#213]
OpenMV2 and OpenMV3 run the same IC2 communication program, but OpenMV3 runs error. The error code is 116.

**Comment by kwagyeman** [comment]
Read this:

https://github.com/openmv/openmv/blob/master/usr/examples/02-Board-Control/arduino_i2c_slave.py

116 is a timeout error. E.g. You don't have pull ups on the I2C wires. Please note that you need to pull try catch statements around your I2C code since MicroPython likes to raise errors on things like I2C timeout versus returning zero. 

Also, please post on the forums.

**Comment by iabdalkader** [comment]
I'm closing this issue and will keep issue #212 open.
