### ISSUE TITLE
UART works not well.

### ISSUE THREAD

**Issue by jsbyysheng** [openmv/openmv#240]
### Steps to reproduce
1.Connect UART3 to my PC by the UART to USB convertor.
2.Use uart.write("Hello World!\r")

### Expected behaviour
I want to get "Hello World!"

### Actual behaviour
I only get "Hello"

### Describe your setup

**Operating system**:
Windows 10
**OpenMV IDE version:**
1.6.0
**OpenMV firmware version:**
2.4.1

**Comment by kwagyeman** [comment]
Hi, can you post the script you are using. The serial port was working fine the last time I used it. Something could have broke.

Sent from my Verizon Wireless 4G LTE Droid
On Jun 6, 2017 8:33 AM, jsbyysheng <notifications@github.com> wrote:
Steps to reproduce

1.Connect UART3 to my PC by the UART to USB convertor.
2.Use uart.write("Hello World!\r")

Expected behaviour

I want to get "Hello World!"

Actual behaviour

I only get "Hello"

Describe your setup

Operating system:
Windows 10
OpenMV IDE version:
1.6.0
OpenMV firmware version:
2.4.1

**Comment by iabdalkader** [comment]
Please try "\n" instead of "\r" or "\r\n"

**Comment by kwagyeman** [comment]
This is legit. The UART doesn't work for my script anymore. Ibrahim can you debug? See board_control/uart_control.py.

When you enabled UART 1 you may have broken this.

**Comment by jsbyysheng** [comment]
> Hi, can you post the script you are using. The serial port was working fine the last time I used it. Something could have broke.

I use the example program as this:
```
import time
from pyb import UART
uart = UART(3, 19200)

while(True):
    uart.write("Hello World!\r")
    time.sleep(1000)
```

> Please try "\n" instead of "\r" or "\r\n"

Have no bussiness with this. I have tried uart.write("HelloWorld!") and I still receive "Hello".

**Comment by kwagyeman** [comment]
Yeah, something is definitely broken. When I tried the same script I got the same result. Ibrahim enabled serial port 1 on the OpenMV Cam M7 which seems to have broke this. Interestingly, serial port 1 doesn't work either.

**Comment by jsbyysheng** [comment]
I'm sorry to say the micropython is so unstable......

**Comment by kwagyeman** [comment]
Ibrahim will fix this in a bit.

**Comment by iabdalkader** [comment]
This issue is Not related to UART1. I disabled UART1 and tested, it's still there. It's Not related to any recent change either (the issue exists in **r2.3**). It seems that UART just timeouts, very short time_char for slow baudrates (<=19200 default timeout_char is 1ms). Setting **timeout_char=10** makes it work fine. I'll increase the default UART timeout.

Just use this for now:
`uart = UART(3, 19200, timeout_char=10)`

**Comment by kwagyeman** [comment]
Ah yes, I remember this being an issue. MP is weird with this. I have no clue why they designed the UART with a timeout on the whole string.

Sent from my Verizon Wireless 4G LTE Droid
On Jun 7, 2017 12:08 PM, Ibrahim Abd Elkader <notifications@github.com> wrote:

This issue is Not related to UART1. I disabled UART1 and tested, it's still there. It's Not related to any recent change either (the issue exists in r2.3). It seems that UART just timeouts, very short time_char for slow baudrates (<=19200 default timeout_char is 1ms). Setting timeout_char=10 makes it work fine. I'll increase the default UART timeout.

Just use this for now:
uart = UART(3, 19200, timeout_char=10)

**Comment by iabdalkader** [comment]
The STHAL libraries accept timeout for the string and for each character (between characters). The character timeout is the issue. BTW I think this is standard, termios works the same. Anyway, closing this issue for now.

**Comment by kwagyeman** [comment]
Maybe update the script?

**Comment by iabdalkader** [comment]
I increased the default timeout_char.
https://github.com/openmv/openmv/commit/a5b25bd5b72311b43a9e3c59e6448c549b1b57c1

**Comment by jsbyysheng** [comment]
OK
