### ISSUE TITLE
Classification/Detection (SSD/RCNN)

### ISSUE THREAD

**Issue by Franzisdrak** [openmv/openmv#399]
Hi there,

I am currently trying to get a custom network built on the M7. Because i don't want to bother setting up Caffe. I am trying to do the whole workflow with Tensorflow and then convert to Caffe.

Can you tell me what Classification network you used for the Cifar10 fast? I just need a crude direction to start from, because i don't want to try the whole process and then find out, that it gets to big for the Heap...

Also i would like to know whether you tried to implement an Detection Network on the OpenMV? 
Cause i have great interest in a low powered approch for Detection.

If you think it would be helpful i could also write down the process TF (Win) ->Caffe 

Kind regards
Franz

**Comment by kwagyeman** [comment]
Hi, I was at ARM Techcon and we met some folks working on Tensor flow and compiling code to a microcontroller. It's a while away from supporting CMSISNN however. So, it's going to be a while for TF.

As for your net size. Right now we can only do classification. In particular, on the M7 the net should be no more than a 64x64 or 32x32 pixel input with about 3 conv layers of 32 filters per layer followed by a pool filter per layer. Then an FC at the end for 2-3 class outputs.

An object detector like YOLO is possible technically but not supported yet.

Finally, I spent 3 days writing the guide about how to use the Caffeine lib. It was a pain to get setup... But, really only the CUDNN part. Caffe installs pretty easy otherwise. I can't do training work for you other than provide the guide.

**Comment by Franzisdrak** [comment]
Hi Kwagyeman,

sounds somewhat promising?! 

The 2-3 class output might work, though i will probably still try to build some sort of detection around it. 

> An object detector like YOLO is possible technically but not supported yet.
Are the layers not suppported? Or didn't you try it (size wise) on the M7?

> Finally, I spent 3 days writing the guide about how to use the Caffeine lib. It was a pain to get setup... 
Did you set it up on WIN? or Linux.

**Comment by kwagyeman** [comment]
On Linux. I bought a deep learning box. Win is no good for this.

**Comment by kwagyeman** [comment]
Hi, its going to be a little bit before all this gets rolled out. The end of the year is really busy for me.

**Comment by kwagyeman** [comment]
This is out out of date. We have TensorFlow support getting ready to launch big time.
