### ISSUE TITLE
DAC.NORMAL mode does not write buffer only once in dac.write_timed

### ISSUE THREAD

**Issue by ajacobs-github** [openmv/openmv#875]
In dac.write_timed with mode=DAC.NORMAL the buffer should be written to the DAC only once, but it looks like the buffer is being written continuously. 

### Steps to reproduce
1.  See attached test code to reproduce
2.  See attached scope trace of DAC with test code 

### Expected behaviour
Buffer should be written to DAC once, not repeatedly

### Actual behaviour
The buffer is written to the DAC continuously.

### Describe your setup
Board: H7
IDE version: 2.6.0
Firmware version: 3.6.7
Windows 10

![Scope Sine wave DAC_NORMAL](https://user-images.githubusercontent.com/63873845/89703449-0bd9a480-d908-11ea-84b2-067a02f10815.jpg)

Code to reproduce the issue:

# Untitled - By: Alan - Fri Aug 7 2020
```

import math
import pyb
import wave
from pyb import DAC
from pyb import Pin

# Setup Debug pin
pin1 = Pin('P1', Pin.OUT_PP)
pin1.value(0)

# setup DAC
dac = DAC(pyb.Pin("P6"), bits=8, buffering = None)

peak = 125      # waveform clips when peak > 126
freq_sine = 20

# create a buffer containing a sine-wave
buf_sine = bytearray(100)
for i in range(len(buf_sine)):
    buf_sine[i] = peak + int((peak-1) * math.sin(2 * math.pi * i / len(buf_sine)))

while(True):

    pin1.value(1)
    pyb.delay(10)
    pin1.value(0)
    # output the sine-wave at frequency
    dac.write_timed(buf_sine, freq_sine * len(buf_sine), mode=DAC.NORMAL)

    pyb.delay(1000)


```

**Comment by iabdalkader** [comment]
You're calling `dac.write_timed` in a loop, am I missing something obvious ?

**Comment by iabdalkader** [comment]
@ajacobs-github Can you please test the attached firmware and let me know if it fixes the issue ? BTW I actually opened an [issue](https://github.com/micropython/micropython/issues/5619)  about this in MicroPython's repo and I completely forgot about it. I used a workaround for this issue which introduced this bug because the default DMA mode using this workaround is fixed to normal or circular, with this fixs it should work now.
[firmware.zip](https://github.com/openmv/openmv/files/5045680/firmware.zip)

**Comment by ajacobs-github** [comment]
@iabdalkader That fixed it.  Thank you for responding and fixing this bug so quickly.  OpenMV and the H7 are terrific.

![image](https://user-images.githubusercontent.com/63873845/89718239-9ce96380-d97a-11ea-8ce5-dbbe51276e1e.png)
